package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            feature {
                type = "project-graphs"
                id = "PROJECT_EXT_5"
                param("series", """
                    [
                      {
                        "type": "valueType",
                        "title": "Build Duration (excluding Checkout Time)",
                        "sourceBuildTypeId": "DreamAppCheck_Build",
                        "key": "BuildDurationNetTime"
                      }
                    ]
                """.trimIndent())
                param("format", "text")
                param("title", "New chart title")
                param("seriesTitle", "Serie")
            }
        }
    }
}
